// Banco da turma. Os cards mostram apenas "nomeGuerra"; o nome completo fica aqui.
// Use datas no formato AAAA-MM-DD e deixe "" quando a informação não for conhecida.
const turma = [
  {nomeGuerra:"Adelson",nome:"Adelson",cidades:["Navegantes-SC"],escala:"28x28",embarque:"2026-08-14",desembarque:"2026-09-11"},
  {nomeGuerra:"Adriano",nome:"Adriano",cidades:["Foz do Iguaçu"],escala:"28x28",embarque:"2026-09-01",desembarque:"2026-09-29"},
  {nomeGuerra:"Alessandra",nome:"Alessandra",cidades:[],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Alexandro",nome:"Alexandro",cidades:["São Sebastião-SP"],escala:"Em terra",embarque:"",desembarque:""},
  {nomeGuerra:"Anderson",nome:"Anderson Moita CLC",cidades:["São José dos Campos"],escala:"90x90",embarque:"2026-10-13",desembarque:"2027-01-13"},
  {nomeGuerra:"Aquino",nome:"Everton de Aquino Peres",cidades:["Fortaleza"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Ariesteu",nome:"Aristeu",cidades:["Rio de Janeiro"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Borges",nome:"Borges",cidades:["São Luís-MA"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Boudakian",nome:"Boudakian",cidades:["Fortaleza"],escala:"28x28",embarque:"",desembarque:"2026-09-18"},
  {nomeGuerra:"Campelo",nome:"Campelo",cidades:["Fortaleza"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Charlene",nome:"Charlene",cidades:["Picos"],escala:"Em terra",embarque:"",desembarque:""},
  {nomeGuerra:"Corrêa",nome:"Corrêa",cidades:["Belém","São Paulo"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Diego",nome:"Diego Barrionuevo Padilla",cidades:["Belém"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Edison",nome:"Edison",cidades:["Recife","São Paulo"],escala:"14x14",embarque:"",desembarque:""},
  {nomeGuerra:"Edvaldo",nome:"Edvaldo",cidades:["Teresina"],escala:"28x28",embarque:"2026-09-23",desembarque:"2026-10-21"},
  {nomeGuerra:"Enrique",nome:"Enrique Arcos",cidades:["Peru"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Evandro",nome:"Evandro Silva Lira",cidades:["Recife"],escala:"Em terra",embarque:"",desembarque:""},
  {nomeGuerra:"Flaviano",nome:"Flaviano",cidades:["Natal"],escala:"28x28",embarque:"2026-08-13",desembarque:"2026-09-10"},
  {nomeGuerra:"Gordon",nome:"Gordon",cidades:["Imperatriz"],escala:"",embarque:"",desembarque:"2026-10-15"},
  {nomeGuerra:"Helneson",nome:"Helneson Menezes",cidades:["Belém"],escala:"14x14",embarque:"2026-10-15",desembarque:"2026-10-29"},
  {nomeGuerra:"Horst",nome:"Alan Horst",cidades:["Rio de Janeiro"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Jackson",nome:"Jackson Efomm",cidades:["Belém"],escala:"28x28",embarque:"2026-08-28",desembarque:"2026-09-25"},
  {nomeGuerra:"Julio",nome:"Julio Holanda",cidades:["Fortaleza"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Leonardo Chagas",nome:"Leonardo Chagas",cidades:["Belém"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Leonardo Silva",nome:"Leonardo Silva Ju Turma",cidades:["Belém"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Lincoln",nome:"Lincoln Efomm",cidades:["Belém"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Lourenço",nome:"Lourenço Turma Cão",cidades:["Recife"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Luciana Maria",nome:"Luciana Maria",cidades:[],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Lucinalva",nome:"Lucinalva",cidades:["Belém"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Mafra",nome:"Glicerio Mafra",cidades:["Santarém"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Mendes",nome:"Mendes",cidades:["Teresina"],escala:"28x28",embarque:"",desembarque:"2026-09-16"},
  {nomeGuerra:"Michel",nome:"Michel",cidades:["Belém"],escala:"28x28",embarque:"",desembarque:"2026-09-29"},
  {nomeGuerra:"Micherlanne",nome:"Micherlanne",cidades:["Fortaleza"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Najer",nome:"Najer",cidades:["Fortaleza"],escala:"28x28",embarque:"2026-08-27",desembarque:"2026-09-24"},
  {nomeGuerra:"Negrão",nome:"Negrão Turma",cidades:["Belém"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Osmar",nome:"Osmar Vaquinha",cidades:["Rio de Janeiro","Macaé"],escala:"28x28 flexível",embarque:"",desembarque:""},
  {nomeGuerra:"Paixão",nome:"Marcelo Paixão",cidades:["Fortaleza"],escala:"28x28",embarque:"2026-09-22",desembarque:"2026-10-20"},
  {nomeGuerra:"Pantoja",nome:"Leonardo Pantoja",cidades:["Belém"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Patrick",nome:"Patrick Teles",cidades:["Manaus"],escala:"Em terra",embarque:"",desembarque:""},
  {nomeGuerra:"Queiroz",nome:"Queiroz Turma",cidades:["Fortaleza"],escala:"14x14",embarque:"2026-09-09",desembarque:"2026-09-23"},
  {nomeGuerra:"Rafael",nome:"Rafael Adeodato",cidades:["Fortaleza"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Raquel",nome:"Raquel",cidades:[],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Robert",nome:"Robert",cidades:["Fortaleza"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Saran",nome:"Diego Saran",cidades:["Belém"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Saulo",nome:"Saulo",cidades:["Coimbra","Recife"],escala:"28x28",embarque:"2026-10-09",desembarque:"2026-11-06"},
  {nomeGuerra:"Severino",nome:"Severino Cidvirino Neto Efomm",cidades:[],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Viana",nome:"Viana",cidades:["Belém"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Vinente",nome:"Jefferson Vinente",cidades:["Belém"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Vieira",nome:"Rodrigo Vieira",cidades:["Belém"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Wallace",nome:"Wallace",cidades:["Picos"],escala:"28x28",embarque:"",desembarque:"2026-09-16"},
  {nomeGuerra:"Wanderley",nome:"Wanderley Turma",cidades:["Belém"],escala:"14x14",embarque:"2026-09-11",desembarque:"2026-09-25"},
  {nomeGuerra:"Weider",nome:"Weider Serafim",cidades:["Picos"],escala:"",embarque:"",desembarque:""},
  {nomeGuerra:"Ximenes",nome:"Rafael Ximenes",cidades:["Fortaleza"],escala:"Em terra",embarque:"",desembarque:""},
  {nomeGuerra:"Yanes",nome:"Yanes",cidades:["Venezuela"],escala:"",embarque:"",desembarque:""}
];
